"""empty message

Revision ID: 1063f6780afd
Revises: fc6a67dca205
Create Date: 2019-11-28 17:43:58.586622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1063f6780afd'
down_revision = 'fc6a67dca205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'password_fgj')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password_fgj', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
