"""empty message

Revision ID: 184bbc82f45f
Revises: 9ab4bd6cdfb4
Create Date: 2019-11-28 16:11:40.128529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '184bbc82f45f'
down_revision = '9ab4bd6cdfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('usuario', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'updated_at')
    op.drop_column('usuario', 'created_at')
    # ### end Alembic commands ###
