"""empty message

Revision ID: 4b77c987e993
Revises: bdead55015aa
Create Date: 2019-11-28 16:07:09.861041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b77c987e993'
down_revision = 'bdead55015aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('firs_name', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(create_constraint=100), nullable=True))
    op.add_column('usuario', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('usuario', sa.Column('password', sa.String(length=100), nullable=True))
    op.drop_column('usuario', 'nome')
    op.drop_column('usuario', 'senha')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('senha', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('usuario', sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'password')
    op.drop_column('usuario', 'last_name')
    op.drop_column('usuario', 'is_admin')
    op.drop_column('usuario', 'firs_name')
    # ### end Alembic commands ###
