"""empty message

Revision ID: a9494165f03f
Revises: be5969f7b86b
Create Date: 2019-11-28 16:25:19.095829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9494165f03f'
down_revision = 'be5969f7b86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('has_admin', sa.Boolean(create_constraint=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'has_admin')
    # ### end Alembic commands ###
