"""empty message

Revision ID: bdead55015aa
Revises: dea387153bc3
Create Date: 2019-11-28 14:58:00.867677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdead55015aa'
down_revision = 'dea387153bc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('macaco')
    op.drop_column('usuario', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_table('macaco',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('senha', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('senha_oisd', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='macaco_pkey')
    )
    # ### end Alembic commands ###
