"""empty message

Revision ID: dea387153bc3
Revises: f8d52a10298d
Create Date: 2019-11-28 00:18:50.009013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dea387153bc3'
down_revision = 'f8d52a10298d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('macaco', sa.Column('senha_oisd', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('macaco', 'senha_oisd')
    # ### end Alembic commands ###
