"""empty message

Revision ID: e1beba1830c7
Revises: fbf075e2dacc
Create Date: 2019-11-28 16:42:05.265622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1beba1830c7'
down_revision = 'fbf075e2dacc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('password_fgj', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'password_fgj')
    # ### end Alembic commands ###
